- name: package upgrade
  shell: $HOME/ci-tools/ci-update-freebsd devel

- name: check pre-upgrade status
  stat: path=/root/.pre_upgrade_done
  register: preupgrade

- meta: end_play
  when: preupgrade.stat.exists == False

- name: install kernel
  shell: cd /usr/src && make installkernel KERNCONF=GENERIC-NODEBUG

- name: reboot after kernel install
  shell: sleep 2 && /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  register: rebootkernel

- name: wait for servers to come back after reboot
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay=90 timeout=300
  when: rebootkernel.changed

- name: update config files
  shell: mergemaster -a

- name: install userland
  shell: cd /usr/src && make installworld

- name: reboot after userland install
  shell: sleep 2 && /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  register: rebootuserland

- name: wait for servers to come back after reboot
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay=90 timeout=300
  when: rebootuserland.changed

- name: clean old files
  shell: cd /usr/src && make BATCH_DELETE_OLD_FILES=yes delete-old delete-old-libs

- name: reboot after config updates and old files removal
  shell: sleep 2 && /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  register: rebootlast

- name: wait for servers to come back after reboot
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay=90 timeout=300
  when: rebootlast.changed

- name: clear pre upgrade status
  file:
    path: /root/.pre_upgrade_done
    state: absent
