- name: package upgrade
  shell: $HOME/ci-tools/ci-update-freebsd devel

- name: check pre-upgrade status
  stat: path=/root/.pre_upgrade_done
  register: preupgrade

- meta: end_play
  when: preupgrade.stat.exists == False

- name: install kernel
  shell: cd /usr/src && make installkernel KERNCONF=GENERIC-NODEBUG

- name: reboot after kernel install
  reboot:
    reboot_timeout: 1800

- name: update config files
  shell: mergemaster -a

- name: install userland
  shell: cd /usr/src && make installworld

- name: reboot after userland install
  reboot:
    reboot_timeout: 1800

- name: clean old files
  shell: cd /usr/src && make BATCH_DELETE_OLD_FILES=yes delete-old delete-old-libs

- name: reboot after config updates and old files removal
  reboot:
    reboot_timeout: 1800

- name: clear pre upgrade status
  file:
    path: /root/.pre_upgrade_done
    state: absent
